name: CI_Pipeline

on:
  push:
    branches: ["main", "prod"]
  pull_requests:
    branches: ["main", "prod"]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

  steps:
    - name: Checkout branche
      uses: actions/checkout@v5

    - name: Setup node-18
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Run test
      run: npm run test
